global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'doanminhquang006@gmail.com'
  smtp_auth_username: 'doanminhquang006@gmail.com'
  smtp_auth_password: 'jfdduwwyecwtmukz'
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - to: 'doanminhquang006@gmail.com'
        send_resolved: true
        headers:
          Subject: '[ALERT] {{ .GroupLabels.alertname }} - {{ .Status | toUpper }}'
