#!/bin/bash
mysql -u root -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL
CREATE DATABASE IF NOT EXISTS ${APP_DB_NAME};
GRANT ALL PRIVILEGES ON ${APP_DB_NAME}.* TO '${APP_DB_USER}'@'%' IDENTIFIED BY '${APP_DB_PASSWORD}';
FLUSH PRIVILEGES;
EOSQL
